### ISSUE TITLE
Tracking progress

### ISSUE THREAD

**Issue by paulawojciechowska** [paulawojciechowska/plant-card#1]
- [x]  Home layout
- [x]  Cards layout
- [x]  Card element
- [x]  Responsive layout
- [x]  Gallery layout
- [ ]  Zoom gallery view 
- [x]  Add dynamics to card component
- [x]  Login modal
- [ ]  Add plant modal
- [ ]  Details information modal
- [ ]  Replace hard-coded data
- [ ]  Loggin in
- [ ]  Backend (firebase/mongoDB)
